### ISSUE TITLE
Queen of Pain Rework [7 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#604]
-------------------------

TALENTS:
Remove:
+20% Blink Scream damage
+100% Delightful Torment effect
+35% Sonic Wave absorption
+100 Scream radius
+50% Sonic Wave start/end radius.
+50% Scream of Pain damage reflected
-2 Blink cooldown

Change:
Scream of Pain applies Shadow Strike on enemies hit -> Auto attacking an enemy unit that is not affected by Shadow Strike applies a Shadow Strike on it.

Apply:
1. Shadow Strike's target releases a Scream of Pain in 400 radius around it every 4 seconds. This scream is not applied on the target itself.
2. Delightful Torment now also increases Queen of Pain's attack speed by 10 each time she procs it. Independent stacks, each lasting 5 seconds.
3. Sonic Wave's "waves" each deal a portion of the damage as a different damage instance, instead of one big damage instance. The total of all damage instances is equal to the normal damage.
4. Blink's Scream and Scream of Pain apply confusion (kinda like R's aghs), their 2 next orders are inverted.
5. Scream of Pain triggers a Shadow Strike instance when hitting enemies affected by Shadow Strike
6. If Queen of Pain is in 1200 AoE of an enemy affected by Shadow Strike, she gains fogvision of it.
7. Blink can be cast twice quick in succession but cooldown is increased accordingly.

**Comment by fcalife** [comment]
Considerations while implementing this, @Shushishtok:

1a. Should the Shadow Strike-based Scream of Pain's radius be the same as the normal Scream of Pain (475), for the sake of consistency between them?

1b. How about making the scream trigger every time the target is damaged, instead of every 4 seconds? Would make more sense, since the target is screaming due to the pain. The scream can be weaker than normal, to keep damage over time the same.

3. Do you mean the visual waves (which are about 4-5, kinda hard to tell)? That's the only thing I can think of here.

4. That's fine, but I'd argue we need a stronger visual indicator that people are dazed/confused (perhaps the big "?" deny symbol they introduced recently?)

**Comment by fcalife** [comment]
7. Why not simply add 2 charges to blink (similar to AM's)?

**Comment by Shushishtok** [comment]
Done!
